#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GamerShuffle.Resource", IsApplication=true)]

namespace GamerShuffle
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int genres_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int platforms_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int raitings_array = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int btnEnter = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int btnNintendoSwitch = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int btnPs4 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btnXbox1 = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int gameListView = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int gameTextView = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int genreTextView = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int genresTextView = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int imageView1 = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int nameTextView = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int platformTextView = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int relativeLayout1 = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int summaryTextView = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GameList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GameListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int searchScreen = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int game_name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int genre_name = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int genre_select = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int platform_name = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int platform_select = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int raiting_select = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
